# Generated by Django 3.1.7 on 2021-03-17 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='地址')),
                ('contact_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('contact_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('contact_postalcode', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮编')),
                ('about_me', models.CharField(blank=True, max_length=2000, null=True, verbose_name='关于我')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
