# Generated by Django 3.1.7 on 2021-03-19 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_info',
            unique_together={('user',)},
        ),
        migrations.CreateModel(
            name='stock_sz_basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk', models.CharField(max_length=150, verbose_name='板块')),
                ('gsqc', models.CharField(max_length=150, verbose_name='公司全称')),
                ('ywmc', models.CharField(max_length=150, verbose_name='英文名称')),
                ('zcdz', models.CharField(max_length=150, verbose_name='注册地址')),
                ('dq', models.CharField(max_length=150, verbose_name='地区')),
                ('sf', models.CharField(max_length=150, verbose_name='省份')),
                ('cs', models.CharField(max_length=150, verbose_name='城市')),
                ('sshy', models.CharField(max_length=150, verbose_name='所属行业')),
                ('gswz', models.CharField(max_length=150, verbose_name='公司网址')),
                ('agdm', models.CharField(blank=True, max_length=6, null=True, verbose_name='A股代码')),
                ('agjc', models.CharField(blank=True, max_length=150, null=True, verbose_name='A股简称')),
                ('agssrq', models.DateField(blank=True, null=True, verbose_name='A股上市日期')),
                ('agzgb', models.CharField(max_length=150, verbose_name='A股总股本')),
                ('agltgb', models.CharField(max_length=150, verbose_name='A股流通股本')),
                ('bgdm', models.CharField(blank=True, max_length=6, null=True, verbose_name='B股代码')),
                ('bgjc', models.CharField(blank=True, max_length=150, null=True, verbose_name='B股简称')),
                ('bgssrq', models.DateField(blank=True, null=True, verbose_name='B股上市日期')),
                ('bgzgb', models.CharField(default=0, max_length=150, verbose_name='B股总股本')),
                ('bgltgb', models.CharField(default=0, max_length=150, verbose_name='B股流通股本')),
            ],
            options={
                'unique_together': {('bk', 'gsqc')},
            },
        ),
    ]
